### ISSUE TITLE
Optimized Code

### ISSUE THREAD

**Issue by EWE07** [LunasAWolf/SusBot9000#1]
That isn't a optimized code
```js
  const args = message.content.slice(prefix.length).trim().split(/ + /g);
  const cmd = args.shift().toLowerCase();
  const command = client.commands.get(cmd);
  if (command) {
    if (!message.content.startsWith(prefix)) return; // the problem is here 
```

I suggest you doing this:
```js 
if (!message.content.startsWith(prefix)) return; // now if message isn't starts with prefix, he don't execute a lot of code .

  const args = message.content.slice(prefix.length).trim().split(/ + /g);
  const cmd = args.shift().toLowerCase();
  const command = client.commands.get(cmd);

  if (command) {
    
```

**Comment by Ellavated** [comment]
Although this would usually be an effective change, in this case the bot needs to be able to continue with the else statement.
```js
if (command) {
  ...
} else {
  ...
}
```

Instead I will be able to change it to this instead to help with optimization.
```js
if (message.content.startsWith(prefix)) {
    const args = message.content.slice(prefix.length).trim().split(/ + /g);
    const cmd = args.shift().toLowerCase();
    const command = client.commands.get(cmd);
    ...
} else {
  ...
}
```
  
  Thanks for the help!

**Comment by EWE07** [comment]
And that puts the content of else before the message.content.startsWith?


(Sorry my bad english :0)

**Comment by Ellavated** [comment]
The change I made will instead of checking for the prefix then returning it moves the else from the `if (command)` statement and places it under the new `message.content.startsWith()` statement allowing the bot to still respond to the messages that it is allowed to that aren't commands. Apologies if I misread what you are trying to say here.
